[tool.poetry]
name = "opb-etl"
version = "0.1.0"
description = ""
authors = ["Quenio <quenio@hey.com>"]
readme = "README.md"
packages = [{include = "opb_etl"}]

[tool.poetry.dependencies]
python = "^3.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
